[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]  # isort
extend-ignore = ["E501"]  # si mantengo 100 cols
src = ["app","tests"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
disallow_untyped_defs = true
no_implicit_optional = true
ignore_missing_imports = true
show_error_codes = true
pretty = true

[tool.bandit]
skips = ["B101"]  # permitir assert en tests

[tool.radon]
cc_min = "A"

[tool.xenon]
max_absolute = "B"
max_average = "A"
max_modular = "B"
